name: flutter_news_service
description: A Dart package designed for accessing worldwide news data from NewsAPI.org. It can filter news by keyword, source, language and more. Ideal for news-based applications.

# The next line is a link to your package's online repository (if it has one).
repository: https://github.com/chuyentt/flutter_news_service
version: 1.0.3

environment:
  # The Dart SDK version that your package is compatible with.
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  # The http package provides a set of high-level functions for use with "http" requests.
  http: ^1.0.0

dev_dependencies:
  # The lints package provides recommended lint rules.
  lints: ^2.0.0
  # The test package provides a core framework for writing tests in Dart.
  test: ^1.21.0
  # The mockito package provides a framework for mocking objects in Dart.
  mockito: ^5.4.2
  # The build_runner package provides a way to generate files using Dart code, outside of pub and Flutter.
  build_runner: ^2.0.0
